### PR TITLE
Rust 2018, cargo fmt and fix some warnings

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by expenses** [comment]
I'm hesitant to merge this as these changes don't affect people who use the crate.

**Comment by ghost** [comment]
It's true that it won't magically correct bugs, but i think it would help to follow rust on it's style and on rust 2018. Being prepare for the future could help maintain the crate over time and rust 2018 is already 3 years old.

**Comment by expenses** [comment]
This crate isn't being actively developed, and as a result I don't think it needs to be up to date with the currently rust style guide. I'm going to close this for now.

**Comment by ghost** [comment]
Just to informed you, i will retired it from fedora since it is not developed anymore. feel free to take package if you want.

**Pull request closed without merging**
